version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      # Database configuration with fallback values
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-auth_db}
      - DB_USER=${DB_USER:-auth_user}
      - DB_PASSWORD=${DB_PASSWORD:-auth_password}
