version: '3.8'

services:
  auth:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - SECRET_KEY=dev_secret_key  # For development only
      - JWT_SECRET_KEY=dev_jwt_secret  # For development only
    command: flask run --host=0.0.0.0
    networks:
      - auth_network

networks:
  auth_network:
    driver: bridge